### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by getaclue** [offirgolan/ember-burger-menu#22]
Hey guys,

Was having trouble making this work in my project, so I decided to create a brand new 2.10 project to see if I can get it to work... and I still cannot.

What step am I missing?

I basically did:
```
ember new dummy
cd dummy
ember install ember-burger-menu
ember g template application
ember g template index
```

then I went into application template and pasted the code from the documentations (just changed the links to index):
```
{{#burger.menu as |burger|}}
  {{#burger.menu itemTagName="li" as |menu|}}
    <a {{action burger.state.actions.close}} class="icon-close"></a>

    <ul>
      {{#menu.item}}
        {{link-to 'index' 'index'}}
      {{/menu.item}}

      {{#menu.item}}
        {{link-to 'index' 'index'}}
      {{/menu.item}}

      {{#menu.item}}
        {{link-to 'index' 'index'}}
      {{/menu.item}}
    </ul>
  {{/burger.menu}}

  {{#burger.outlet}}
    <a class="icon-menu" {{action burger.state.actions.toggle}}></a>
    {{outlet}}
  {{/burger.outlet}}
{{/burger.menu}}
```

and went into index and pasted
```
hi from index
```

when I navigate to `localhost:4200` I see a blank page; but when I scroll down then I see my `hi from index`

Bit confused on what am I doing wrong... I really would love to get this to work.

Thank you
Alex

**Comment by whiskeysauer** [comment]
The setup procedure looks okay, from what I can recall when I did my testing.

A couple things to do though that will likely help you know where the problem is.

- If you have not already done so, install [Ember Inspector](https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi?hl=en). That will help you see what templates are rendering and from which routes.
- Use the Developer Tools (Chrome F12) and see if there are any errors in the console. Also inspect the page elements and see if the menu is actually rendering. If the template is rendering and there are no console errors, then likely some CSS is not being injected. In other words, the elements are there but the CSS is not.

I would need to go open up my test app to see if I can spot anything else I can offer as a tip. Try those things first though and see if there's anything obvious jumping out at you.

PS: The fact that your "hi from index" is rendering down the page tells me that maybe you are going to see some console errors or css is not there. The menu is "off-canvas", so it should not be pushing anything down the page like that.

**Comment by getaclue** [comment]
@whiskeysauer thanks for the feedback!

Yeap, I definitely did all of those things before coming back here. No errors =(
Since I am strapped for time, I ended up rolling out my own slide out menu... but I will check back here =)

**Comment by offirgolan** [comment]
@getaclue your have a typo in your code.

```hbs
{{#burger.menu as |burger|}}
  ...
{{/burger.menu}}
```

Should be:

```hbs
{{#burger-menu as |burger|}}
  ...
{{/burger-menu}}
```

**Comment by getaclue** [comment]
@offirgolan that partly worked thanks!! 
That got the actual menu to show up (had to force it to open by default).
How do I get the menu button (the hamburger icon) to show up so I can toggle the actual menu?

**Comment by offirgolan** [comment]
@getaclue you already have a button in the `{{burger.outlet}}`

```hbs
<a class="icon-menu" {{action burger.state.actions.toggle}}></a>
```

I'm assuming you cant see that button because you dont have an `icon-menu` class. Try changing it to this:

```hbs
<button {{action burger.state.actions.toggle}}>Toggle</button>
```

**Comment by getaclue** [comment]
@offirgolan oh okay, that makes sense... sorry I guess I misunderstood the fact that the `icon-menu` doesn't come with this.

Everything works now!!
Thank you for this menu!

Cheers
Alex

**Comment by offirgolan** [comment]
@getaclue no worries! Glad everything is working now 😸
